language: node_js
node_js:
  - "6"
before_install:
  - npm install -g serverless
  - echo $'APP_NAME=tranium-travis-ci\nSTAGE=testing\nPORT=3000\nS3_BUCKET=tranium-travis-ci\n' > .env
after_script:
  - npm run test:coverage
  - npm i coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm run deploy || exit 1
  - npm run remove || exit 1
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4af54608b616b3f199f5